//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thicuoiky
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public long MaChiTietHD { get; set; }
        public string MaGiay { get; set; }
        public int SoLuongMua { get; set; }
        public long MaHoaDon { get; set; }
        public Nullable<bool> damua { get; set; }
    
        public virtual giay giay { get; set; }
        public virtual hoadon hoadon { get; set; }
    }
}
