//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thicuoiky
{
    using System;
    using System.Collections.Generic;
    
    public partial class giay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public giay()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public string magiay { get; set; }
        public string tengiay { get; set; }
        public Nullable<long> soluong { get; set; }
        public Nullable<long> gia { get; set; }
        public string maloai { get; set; }
        public string anh { get; set; }
        public string ncc { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<long> size { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual loai loai { get; set; }
    }
}
