//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thicuoiky
{
    using System;
    using System.Collections.Generic;
    
    public partial class lichsu
    {
        public string tengiay { get; set; }
        public System.DateTime NgayMua { get; set; }
        public int SoLuongMua { get; set; }
        public Nullable<long> gia { get; set; }
        public Nullable<long> thanhtien { get; set; }
        public long makh { get; set; }
    }
}
