//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thicuoiky
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;

    public partial class QLGiayEntities : DbContext
    {
        public QLGiayEntities()
            : base("name=QLGiayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<DangNhap> DangNhaps { get; set; }
        public virtual DbSet<giay> giays { get; set; }
        public virtual DbSet<hoadon> hoadons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<loai> loais { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<lichsu> lichsus { get; set; }
        public virtual DbSet<xacnhanmua> xacnhanmuas { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }

        internal void Refresh(object clientWins, object yourentity)
        {
            throw new NotImplementedException();
        }

        internal void Refresh(RefreshMode clientWins, object yourentity)
        {
            throw new NotImplementedException();
        }
    }
}
